# Generated by Django 3.2.6 on 2021-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'TypesOfCorrespondence',
            },
        ),
    ]
