# Generated by Django 3.2.6 on 2021-09-04 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import webshop_base.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop_base', '0002_typeofcorrespondence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to=webshop_base.models.Customer.user_images_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fathers_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_newsLetter_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ref_category',
            field=models.ManyToManyField(to='webshop_base.CustomerCategory'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ref_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='products_visible_for_this_category',
            field=models.ManyToManyField(to='webshop_base.ProductItem'),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='new_post_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='new_post_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customernewpostdata',
            name='ref_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.customer'),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='ref_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.customer'),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='price_of_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='followup_orders_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='followup_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='ref_mailing_action',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.mailingaction'),
        ),
        migrations.AddField(
            model_name='linkfollowup',
            name='visits_quanitiy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='number_of_links_sent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='ref_customer_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.customercategory'),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='ref_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.mailmessage'),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='ref_rebate_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.rebateaction'),
        ),
        migrations.AddField(
            model_name='mailingaction',
            name='url_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='message_subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='message_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.deliveryoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_link_followup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.linkfollowup'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_promocode_followup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.promocodeaction'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='bg_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='send_mail_on_init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(null=True, upload_to=webshop_base.models.ProductCategory.product_category_path),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_products',
            field=models.ManyToManyField(to='webshop_base.ProductItem'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(null=True, upload_to=webshop_base.models.ProductImage.product_directory_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='ref_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.productitem'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitem',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='measurementUnit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='quantityInStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='sellingUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='productorder',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productorder',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productorder',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='quantity_of_SU',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ref_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ref_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.productprice'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ref_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.productitem'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productprice',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productprice',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_for_one_SU',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='quantity_SU_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='quantity_SU_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='ref_customer_group',
            field=models.ManyToManyField(to='webshop_base.CustomerCategory'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='ref_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.productitem'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='additional_feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='date_of_return',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='quantity_SU_returned',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='reason_for_return',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='ref_product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.productorder'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='ref_return_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.returnstatus'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_confirmed_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='ref_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.customer'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='ref_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.productitem'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_image',
            field=models.ImageField(null=True, upload_to=webshop_base.models.ProductReview.user_images_path),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='followup_orders_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='followup_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='promocode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='ref_rebate_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.rebateaction'),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='StreetNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='flat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='oblast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='postalCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='raion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='ref_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.customer'),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='settlement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pstaladdress',
            name='staircase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebate',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='discount_mutiplicator',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rebate',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebate',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='ref_customerGroup',
            field=models.ManyToManyField(to='webshop_base.CustomerCategory'),
        ),
        migrations.AddField(
            model_name='rebate',
            name='ref_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.productitem'),
        ),
        migrations.AddField(
            model_name='rebate',
            name='ref_productCategory',
            field=models.ManyToManyField(to='webshop_base.ProductCategory'),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='dateTo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='from_SU_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='is_promo_code_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='ref_rebate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_base.rebate'),
        ),
        migrations.AddField(
            model_name='rebateaction',
            name='toSuQuantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='bg_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returnstatus',
            name='send_mail_on_init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='bg_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='typeofcorrespondence',
            name='send_mail_on_init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='ref_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webshop_base.mailmessage'),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='ref_type_of_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop_base.typeofcorrespondence'),
        ),
        migrations.AddField(
            model_name='usercorrespondence',
            name='ref_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
